# Fundamentos de TensorFlow

En este notebook se verá conceptos básico sobre Tensorflow.  

Tensorflow es una biblioteca que está enfocada en la construcción de modelos de aprendizaje automático. 

In [1]:
# Importamos Tensorflow
import tensorflow as tf

In [2]:
# Verificamos la versión que vamos a usar
print(tf.__version__)

2.10.1


## Creación de Tensores

Un tensor es un arreglo multidimensional de datos.

Haremos uso de la función `tf.constant` para crear tensores.
Esta tiene los siguientes parámetros:  
* value: Objeto.
* dtype: Tipo de dato de valor, si no se le especifica se deducirá de value
* shape: Forma del Tensor resultante (Opcional)

Para asignar el dtype, tener en cuenta la siguiente tabla.
| Número de bits    | Valor mínimo | Valor máximo |
| ----------------- | ------------ | ------------ |
| 8 bits            | -128         | 127          |
| 16 bits           | -32768       | 32767        |
| 32 bits           | -2147483648  | 2147483647   |
| 64 bits           | –2^63        | 2^63 - 1     |

### Scalar

Creamos un tensor de tipo escalar. Le pasaremos un número como argumentos de `tf.constant`.  
Los tensores escalares no tienen dimensión (0) ni forma (None).

In [3]:
# Creamos el primer tensor
scalar = tf.constant(77, dtype=tf.int16, shape=None)
scalar

<tf.Tensor: shape=(), dtype=int16, numpy=77>

In [4]:
# Verificamos las dimensiones del tensor creado anteriormente
scalar.ndim

0

### Vector

Un Tensor del tipo vector tiene una dimensión.

In [5]:
# Creamos un vector
vector = tf.constant([10,8,6], dtype=tf.int16)
vector

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([10,  8,  6], dtype=int16)>

In [6]:
# Verificamos las dimensiones del tensor creado anteriormente
vector.ndim

1

### Matriz

Un tensor del tipo matriz tiene dos dimensiones.
Los Tensores (en general) pueden tener más de dos dimensiones.

In [7]:
# Creamos una matriz
matrix = tf.constant([[130,5],
                      [3,6],
                      [2,1]], dtype=tf.int16)
matrix

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[130,   5],
       [  3,   6],
       [  2,   1]], dtype=int16)>

In [8]:
matrix.ndim

2